#!/bin/bash

#Shared constants

PROGRAM_PATH=$(dirname $(realpath "$0"))
BASE_URL='http://localhost:3000'

# Address of listening bot
MY_ADDRESS='BEK76oMDxttaiZCCsLxzr2Wb2kyKowhkL3'
LOGFILE="$PROGRAM_PATH/logfile"

# Adjust prices for OPS
COST_FOLLOW=10
COST_LIKE=5
COST_RETWEET=10
COST_MENTION=20

# Indicies for OPS
FOLLOW=1
LIKE=2
RETWEET=3
MENTION=4
