#!/bin/bash

PROGRAM_PATH=$(dirname $(realpath "$0"))
source "$PROGRAM_PATH/constants"

MAX_LEN=80

showusage() {
	echo "Usage: $0 -f <Operation> -i <id> [ -m <message> ]"
	echo ""
	echo -e "Operation:\tfollow, like, retweet, mention"
	echo -e "id:\t\tusername or tweetid"
	echo -e "message:\tOnly applicaple with -f mention"
	exit
}


while getopts "f:i:m:" options; do

		case ${options} in
				"f") OP=${OPTARG} ;;
				"i") id=${OPTARG} ;;
				"m") msg=${OPTARG} ;;
		esac
done

case "$OP" in
		"follow") 	if [[ "$id" == "" ]]; then showusage; fi
					str="1:$id" 
					cost=$COST_FOLLOW ;;
		"like") 	if [[ "$id" == "" ]]; then showusage; fi
					str="2:$id"
					cost=$COST_LIKE ;;
		"retweet") 	if [[ "$id" == "" ]]; then showusage; fi
					str="3:$id" 
					cost=$COST_RETWEET ;;
		"mention") 	
					if [[ "$id" == ""  ]] || [[ "$msg" == "" ]]; then showusage; fi
					str="4:$id:$msg"
					cost=$COST_MENTION ;;
				*)	showusage
esac

echo -e "Input string: $str\n\n"

if [[ ! -f "$PROGRAM_PATH/encode" ]]; then
		echo "Unable to encode"
		exit 1
fi

# If encoded string is longer than 80 bytes, shorten.
if [[ ! ${#str} -le $MAX_LEN ]]; then
		str=${str:0:$MAX_LEN}
		echo -e "String to long!\nShortened to: $str\n"
fi

encoded=$("$PROGRAM_PATH/encode" "$str")

echo -e "Encoded string $encoded\n"

echo -e "Template rawtransaction string:\n\n"

echo "'[{\"txid\":\"id\",\"vout\":n}]' '{\"$MY_ADDRESS\":$cost, \"data\":\"$encoded\"}'"
